### ISSUE TITLE
Normalize the `uniqueFooIdentifier()` functions

### ISSUE THREAD

**Issue by nexushoratio** [nexushoratio/userscripts#251]
A bit all over the place.

- [ ] We should figure out if using `if (element) {...}` defensively, or not
- [ ] Probably always start with `let content = element.innerText;`, then fine tune
- [ ] Normalize name if always include associated `Scroller` (or *Shared* in the exceptional case of `Feed`)
- [ ] Document above in either STYLE-GUIDE or `Scroller` itself

**Comment by nexushoratio** [comment]
Burn down list for checking duplicates:

- [x] Feed.uniqueCommentIdentifier
- [x] Feed.uniquePostIdentifier
- [x] MyNetwork.uniqueCollectionIdentifier
- [x] MyNetwork.uniqueIndividualsIdentifier
- [x] LinkedIn.ckeyIdentifier (InvitationManager)
- [x] Jobs.uniqueJobIdentifier
- [x] LinkedIn.ckeyIdentifier (Jobs)
- [x] JobsCollections.uniqueDetailsIdentifier
- [x] JobsCollections.uniqueJobIdentifier
- [x] JobsCollections.uniquePaginationIdentifier (See #300)
- [x] JobsView.uniqueCardIdentifier
- [x] JobsView.uniqueEntryIdentifier (See #301)
- [x] Messaging.uniqueConvoCardsIdentifier
- [x] Messaging.uniqueMessageIdentifier
- [x] Notifications.uniqueNotificationIdentifier
- [x] Profile.uniqueEntryIdentifier (See #302)
- [x] Profile.uniqueSectionIdentifier
- [x] Events.uniqueCollectionIdentifier
- [x] Events.uniqueEventIdentifier
- [x] SearchResultsPeople.uniquePaginationIdentifier
- [x] SearchResultsPeople.uniqueResultIdentifier

**Comment by nexushoratio** [comment]
Burn down list for checking stability:

- [x] Feed.uniquePostIdentifier
- [x] Feed.uniqueCommentIdentifier
- [x] MyNetwork.uniqueCollectionIdentifier (See #305)
- [x] MyNetwork.uniqueIndividualsIdentifier (See #306)
- [x] LinkedIn.ckeyIdentifier (InvitationManager) (See #307)
- [x] LinkedIn.ckeyIdentifier (Jobs) (See #309)
- [x] Jobs.uniqueJobIdentifier (See #310)
- [x] JobsCollections.uniqueDetailsIdentifier
- [x] JobsCollections.uniqueJobIdentifier
- [x] JobsCollections.uniquePaginationIdentifier
- [x] JobsView.uniqueCardIdentifier
- [x] JobsView.uniqueEntryIdentifier
- [x] Messaging.uniqueConvoCardsIdentifier
- [x] Messaging.uniqueMessageIdentifier
- [x] Notifications.uniqueNotificationIdentifier
- [x] Events.uniqueCollectionIdentifier
- [x] Events.uniqueEventIdentifier
- [x] SearchResultsPeople.uniquePaginationIdentifier
- [x] SearchResultsPeople.uniqueResultIdentifier
- [ ] Profile.uniqueSectionIdentifier
- [ ] Profile.uniqueEntryIdentifier
